
server:
  port: 8081
  servlet:
    context-path: /api

spring:
  kafka:
    group-id: service  
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.value.default.type: com.example.getaway.ApplicationLayer.DTO.RegistrationUserRequest
    consumer:
      group-id: notification

logging:
  level:
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR



