FROM openjdk:22-jdk

WORKDIR /app


COPY ./SecurityMicroservice/target/SecurityMicroservice-0.0.1-SNAPSHOT.jar /app/SecurityMicroservice.jar

EXPOSE 8080
EXPOSE 9091

ENTRYPOINT ["java", "-jar", "SecurityMicroservice.jar"]
