pipeline:
  identifier: Build_MaryHofman_Frankenstein_1740297527487
  name: Build Frankenstein
  orgIdentifier: default
  projectIdentifier: frankenshtain
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1740297496794
        repoName: MaryHofman/Frankenstein
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Docker
        type: CI
