// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: product.proto
// Protobuf Java Version: 4.27.0

package com.example.cartProto;

public final class Product {
  private Product() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      Product.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProductListRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.cartProto.ProductListRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int64 productId = 1;</code>
     * @return A list containing the productId.
     */
    java.util.List<java.lang.Long> getProductIdList();
    /**
     * <code>repeated int64 productId = 1;</code>
     * @return The count of productId.
     */
    int getProductIdCount();
    /**
     * <code>repeated int64 productId = 1;</code>
     * @param index The index of the element to return.
     * @return The productId at the given index.
     */
    long getProductId(int index);
  }
  /**
   * Protobuf type {@code com.example.cartProto.ProductListRequest}
   */
  public static final class ProductListRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.example.cartProto.ProductListRequest)
      ProductListRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 0,
        /* suffix= */ "",
        ProductListRequest.class.getName());
    }
    // Use ProductListRequest.newBuilder() to construct.
    private ProductListRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ProductListRequest() {
      productId_ = emptyLongList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.cartProto.Product.internal_static_com_example_cartProto_ProductListRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.cartProto.Product.internal_static_com_example_cartProto_ProductListRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.cartProto.Product.ProductListRequest.class, com.example.cartProto.Product.ProductListRequest.Builder.class);
    }

    public static final int PRODUCTID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.LongList productId_ =
        emptyLongList();
    /**
     * <code>repeated int64 productId = 1;</code>
     * @return A list containing the productId.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getProductIdList() {
      return productId_;
    }
    /**
     * <code>repeated int64 productId = 1;</code>
     * @return The count of productId.
     */
    public int getProductIdCount() {
      return productId_.size();
    }
    /**
     * <code>repeated int64 productId = 1;</code>
     * @param index The index of the element to return.
     * @return The productId at the given index.
     */
    public long getProductId(int index) {
      return productId_.getLong(index);
    }
    private int productIdMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getProductIdList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(productIdMemoizedSerializedSize);
      }
      for (int i = 0; i < productId_.size(); i++) {
        output.writeInt64NoTag(productId_.getLong(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < productId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(productId_.getLong(i));
        }
        size += dataSize;
        if (!getProductIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        productIdMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.cartProto.Product.ProductListRequest)) {
        return super.equals(obj);
      }
      com.example.cartProto.Product.ProductListRequest other = (com.example.cartProto.Product.ProductListRequest) obj;

      if (!getProductIdList()
          .equals(other.getProductIdList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getProductIdCount() > 0) {
        hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
        hash = (53 * hash) + getProductIdList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.cartProto.Product.ProductListRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.cartProto.Product.ProductListRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.cartProto.Product.ProductListRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.cartProto.Product.ProductListRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.cartProto.Product.ProductListRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.cartProto.Product.ProductListRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.cartProto.Product.ProductListRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.cartProto.Product.ProductListRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.cartProto.Product.ProductListRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.cartProto.Product.ProductListRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.cartProto.Product.ProductListRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.cartProto.Product.ProductListRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.cartProto.Product.ProductListRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.cartProto.ProductListRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.cartProto.ProductListRequest)
        com.example.cartProto.Product.ProductListRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.cartProto.Product.internal_static_com_example_cartProto_ProductListRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.cartProto.Product.internal_static_com_example_cartProto_ProductListRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.cartProto.Product.ProductListRequest.class, com.example.cartProto.Product.ProductListRequest.Builder.class);
      }

      // Construct using com.example.cartProto.Product.ProductListRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        productId_ = emptyLongList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.cartProto.Product.internal_static_com_example_cartProto_ProductListRequest_descriptor;
      }

      @java.lang.Override
      public com.example.cartProto.Product.ProductListRequest getDefaultInstanceForType() {
        return com.example.cartProto.Product.ProductListRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.cartProto.Product.ProductListRequest build() {
        com.example.cartProto.Product.ProductListRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.cartProto.Product.ProductListRequest buildPartial() {
        com.example.cartProto.Product.ProductListRequest result = new com.example.cartProto.Product.ProductListRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.cartProto.Product.ProductListRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          productId_.makeImmutable();
          result.productId_ = productId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.cartProto.Product.ProductListRequest) {
          return mergeFrom((com.example.cartProto.Product.ProductListRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.cartProto.Product.ProductListRequest other) {
        if (other == com.example.cartProto.Product.ProductListRequest.getDefaultInstance()) return this;
        if (!other.productId_.isEmpty()) {
          if (productId_.isEmpty()) {
            productId_ = other.productId_;
            productId_.makeImmutable();
            bitField0_ |= 0x00000001;
          } else {
            ensureProductIdIsMutable();
            productId_.addAll(other.productId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                long v = input.readInt64();
                ensureProductIdIsMutable();
                productId_.addLong(v);
                break;
              } // case 8
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureProductIdIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  productId_.addLong(input.readInt64());
                }
                input.popLimit(limit);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.LongList productId_ = emptyLongList();
      private void ensureProductIdIsMutable() {
        if (!productId_.isModifiable()) {
          productId_ = makeMutableCopy(productId_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated int64 productId = 1;</code>
       * @return A list containing the productId.
       */
      public java.util.List<java.lang.Long>
          getProductIdList() {
        productId_.makeImmutable();
        return productId_;
      }
      /**
       * <code>repeated int64 productId = 1;</code>
       * @return The count of productId.
       */
      public int getProductIdCount() {
        return productId_.size();
      }
      /**
       * <code>repeated int64 productId = 1;</code>
       * @param index The index of the element to return.
       * @return The productId at the given index.
       */
      public long getProductId(int index) {
        return productId_.getLong(index);
      }
      /**
       * <code>repeated int64 productId = 1;</code>
       * @param index The index to set the value at.
       * @param value The productId to set.
       * @return This builder for chaining.
       */
      public Builder setProductId(
          int index, long value) {

        ensureProductIdIsMutable();
        productId_.setLong(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 productId = 1;</code>
       * @param value The productId to add.
       * @return This builder for chaining.
       */
      public Builder addProductId(long value) {

        ensureProductIdIsMutable();
        productId_.addLong(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 productId = 1;</code>
       * @param values The productId to add.
       * @return This builder for chaining.
       */
      public Builder addAllProductId(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureProductIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, productId_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 productId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductId() {
        productId_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.cartProto.ProductListRequest)
    }

    // @@protoc_insertion_point(class_scope:com.example.cartProto.ProductListRequest)
    private static final com.example.cartProto.Product.ProductListRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.cartProto.Product.ProductListRequest();
    }

    public static com.example.cartProto.Product.ProductListRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProductListRequest>
        PARSER = new com.google.protobuf.AbstractParser<ProductListRequest>() {
      @java.lang.Override
      public ProductListRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProductListRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProductListRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.cartProto.Product.ProductListRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProductListItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.cartProto.ProductListItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string listImage = 2;</code>
     * @return The listImage.
     */
    java.lang.String getListImage();
    /**
     * <code>string listImage = 2;</code>
     * @return The bytes for listImage.
     */
    com.google.protobuf.ByteString
        getListImageBytes();

    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string price = 4;</code>
     * @return The price.
     */
    java.lang.String getPrice();
    /**
     * <code>string price = 4;</code>
     * @return The bytes for price.
     */
    com.google.protobuf.ByteString
        getPriceBytes();

    /**
     * <code>string type = 5;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>string type = 5;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>int32 quantity = 6;</code>
     * @return The quantity.
     */
    int getQuantity();

    /**
     * <code>string discount = 7;</code>
     * @return The discount.
     */
    java.lang.String getDiscount();
    /**
     * <code>string discount = 7;</code>
     * @return The bytes for discount.
     */
    com.google.protobuf.ByteString
        getDiscountBytes();
  }
  /**
   * Protobuf type {@code com.example.cartProto.ProductListItem}
   */
  public static final class ProductListItem extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.example.cartProto.ProductListItem)
      ProductListItemOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 0,
        /* suffix= */ "",
        ProductListItem.class.getName());
    }
    // Use ProductListItem.newBuilder() to construct.
    private ProductListItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ProductListItem() {
      listImage_ = "";
      name_ = "";
      price_ = "";
      type_ = "";
      discount_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.cartProto.Product.internal_static_com_example_cartProto_ProductListItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.cartProto.Product.internal_static_com_example_cartProto_ProductListItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.cartProto.Product.ProductListItem.class, com.example.cartProto.Product.ProductListItem.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int LISTIMAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object listImage_ = "";
    /**
     * <code>string listImage = 2;</code>
     * @return The listImage.
     */
    @java.lang.Override
    public java.lang.String getListImage() {
      java.lang.Object ref = listImage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        listImage_ = s;
        return s;
      }
    }
    /**
     * <code>string listImage = 2;</code>
     * @return The bytes for listImage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getListImageBytes() {
      java.lang.Object ref = listImage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        listImage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object price_ = "";
    /**
     * <code>string price = 4;</code>
     * @return The price.
     */
    @java.lang.Override
    public java.lang.String getPrice() {
      java.lang.Object ref = price_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        price_ = s;
        return s;
      }
    }
    /**
     * <code>string price = 4;</code>
     * @return The bytes for price.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPriceBytes() {
      java.lang.Object ref = price_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        price_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object type_ = "";
    /**
     * <code>string type = 5;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 5;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTITY_FIELD_NUMBER = 6;
    private int quantity_ = 0;
    /**
     * <code>int32 quantity = 6;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public int getQuantity() {
      return quantity_;
    }

    public static final int DISCOUNT_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object discount_ = "";
    /**
     * <code>string discount = 7;</code>
     * @return The discount.
     */
    @java.lang.Override
    public java.lang.String getDiscount() {
      java.lang.Object ref = discount_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        discount_ = s;
        return s;
      }
    }
    /**
     * <code>string discount = 7;</code>
     * @return The bytes for discount.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDiscountBytes() {
      java.lang.Object ref = discount_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        discount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(listImage_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, listImage_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(price_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, price_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, type_);
      }
      if (quantity_ != 0) {
        output.writeInt32(6, quantity_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(discount_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, discount_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(listImage_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, listImage_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(price_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, price_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, type_);
      }
      if (quantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, quantity_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(discount_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, discount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.cartProto.Product.ProductListItem)) {
        return super.equals(obj);
      }
      com.example.cartProto.Product.ProductListItem other = (com.example.cartProto.Product.ProductListItem) obj;

      if (getId()
          != other.getId()) return false;
      if (!getListImage()
          .equals(other.getListImage())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getPrice()
          .equals(other.getPrice())) return false;
      if (!getType()
          .equals(other.getType())) return false;
      if (getQuantity()
          != other.getQuantity()) return false;
      if (!getDiscount()
          .equals(other.getDiscount())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + LISTIMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getListImage().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getPrice().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity();
      hash = (37 * hash) + DISCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getDiscount().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.cartProto.Product.ProductListItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.cartProto.Product.ProductListItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.cartProto.Product.ProductListItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.cartProto.Product.ProductListItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.cartProto.Product.ProductListItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.cartProto.Product.ProductListItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.cartProto.Product.ProductListItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.cartProto.Product.ProductListItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.cartProto.Product.ProductListItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.cartProto.Product.ProductListItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.cartProto.Product.ProductListItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.cartProto.Product.ProductListItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.cartProto.Product.ProductListItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.cartProto.ProductListItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.cartProto.ProductListItem)
        com.example.cartProto.Product.ProductListItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.cartProto.Product.internal_static_com_example_cartProto_ProductListItem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.cartProto.Product.internal_static_com_example_cartProto_ProductListItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.cartProto.Product.ProductListItem.class, com.example.cartProto.Product.ProductListItem.Builder.class);
      }

      // Construct using com.example.cartProto.Product.ProductListItem.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        listImage_ = "";
        name_ = "";
        price_ = "";
        type_ = "";
        quantity_ = 0;
        discount_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.cartProto.Product.internal_static_com_example_cartProto_ProductListItem_descriptor;
      }

      @java.lang.Override
      public com.example.cartProto.Product.ProductListItem getDefaultInstanceForType() {
        return com.example.cartProto.Product.ProductListItem.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.cartProto.Product.ProductListItem build() {
        com.example.cartProto.Product.ProductListItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.cartProto.Product.ProductListItem buildPartial() {
        com.example.cartProto.Product.ProductListItem result = new com.example.cartProto.Product.ProductListItem(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.cartProto.Product.ProductListItem result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.listImage_ = listImage_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.price_ = price_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.quantity_ = quantity_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.discount_ = discount_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.cartProto.Product.ProductListItem) {
          return mergeFrom((com.example.cartProto.Product.ProductListItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.cartProto.Product.ProductListItem other) {
        if (other == com.example.cartProto.Product.ProductListItem.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getListImage().isEmpty()) {
          listImage_ = other.listImage_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getPrice().isEmpty()) {
          price_ = other.price_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.getQuantity() != 0) {
          setQuantity(other.getQuantity());
        }
        if (!other.getDiscount().isEmpty()) {
          discount_ = other.discount_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                listImage_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                price_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                type_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 48: {
                quantity_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 58: {
                discount_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object listImage_ = "";
      /**
       * <code>string listImage = 2;</code>
       * @return The listImage.
       */
      public java.lang.String getListImage() {
        java.lang.Object ref = listImage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          listImage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string listImage = 2;</code>
       * @return The bytes for listImage.
       */
      public com.google.protobuf.ByteString
          getListImageBytes() {
        java.lang.Object ref = listImage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          listImage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string listImage = 2;</code>
       * @param value The listImage to set.
       * @return This builder for chaining.
       */
      public Builder setListImage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        listImage_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string listImage = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearListImage() {
        listImage_ = getDefaultInstance().getListImage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string listImage = 2;</code>
       * @param value The bytes for listImage to set.
       * @return This builder for chaining.
       */
      public Builder setListImageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        listImage_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object price_ = "";
      /**
       * <code>string price = 4;</code>
       * @return The price.
       */
      public java.lang.String getPrice() {
        java.lang.Object ref = price_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          price_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string price = 4;</code>
       * @return The bytes for price.
       */
      public com.google.protobuf.ByteString
          getPriceBytes() {
        java.lang.Object ref = price_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          price_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string price = 4;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        price_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string price = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        price_ = getDefaultInstance().getPrice();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string price = 4;</code>
       * @param value The bytes for price to set.
       * @return This builder for chaining.
       */
      public Builder setPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        price_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 5;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 5;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 5;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        type_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        type_ = getDefaultInstance().getType();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string type = 5;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        type_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private int quantity_ ;
      /**
       * <code>int32 quantity = 6;</code>
       * @return The quantity.
       */
      @java.lang.Override
      public int getQuantity() {
        return quantity_;
      }
      /**
       * <code>int32 quantity = 6;</code>
       * @param value The quantity to set.
       * @return This builder for chaining.
       */
      public Builder setQuantity(int value) {

        quantity_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int32 quantity = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000020);
        quantity_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object discount_ = "";
      /**
       * <code>string discount = 7;</code>
       * @return The discount.
       */
      public java.lang.String getDiscount() {
        java.lang.Object ref = discount_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          discount_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string discount = 7;</code>
       * @return The bytes for discount.
       */
      public com.google.protobuf.ByteString
          getDiscountBytes() {
        java.lang.Object ref = discount_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          discount_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string discount = 7;</code>
       * @param value The discount to set.
       * @return This builder for chaining.
       */
      public Builder setDiscount(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        discount_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string discount = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDiscount() {
        discount_ = getDefaultInstance().getDiscount();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string discount = 7;</code>
       * @param value The bytes for discount to set.
       * @return This builder for chaining.
       */
      public Builder setDiscountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        discount_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.cartProto.ProductListItem)
    }

    // @@protoc_insertion_point(class_scope:com.example.cartProto.ProductListItem)
    private static final com.example.cartProto.Product.ProductListItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.cartProto.Product.ProductListItem();
    }

    public static com.example.cartProto.Product.ProductListItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProductListItem>
        PARSER = new com.google.protobuf.AbstractParser<ProductListItem>() {
      @java.lang.Override
      public ProductListItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProductListItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProductListItem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.cartProto.Product.ProductListItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetProductsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.cartProto.GetProducts)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
     */
    java.util.List<com.example.cartProto.Product.ProductListItem> 
        getItemsList();
    /**
     * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
     */
    com.example.cartProto.Product.ProductListItem getItems(int index);
    /**
     * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
     */
    java.util.List<? extends com.example.cartProto.Product.ProductListItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
     */
    com.example.cartProto.Product.ProductListItemOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.example.cartProto.GetProducts}
   */
  public static final class GetProducts extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.example.cartProto.GetProducts)
      GetProductsOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 0,
        /* suffix= */ "",
        GetProducts.class.getName());
    }
    // Use GetProducts.newBuilder() to construct.
    private GetProducts(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetProducts() {
      items_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.cartProto.Product.internal_static_com_example_cartProto_GetProducts_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.cartProto.Product.internal_static_com_example_cartProto_GetProducts_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.cartProto.Product.GetProducts.class, com.example.cartProto.Product.GetProducts.Builder.class);
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.example.cartProto.Product.ProductListItem> items_;
    /**
     * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.cartProto.Product.ProductListItem> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.example.cartProto.Product.ProductListItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
     */
    @java.lang.Override
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
     */
    @java.lang.Override
    public com.example.cartProto.Product.ProductListItem getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
     */
    @java.lang.Override
    public com.example.cartProto.Product.ProductListItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.cartProto.Product.GetProducts)) {
        return super.equals(obj);
      }
      com.example.cartProto.Product.GetProducts other = (com.example.cartProto.Product.GetProducts) obj;

      if (!getItemsList()
          .equals(other.getItemsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.cartProto.Product.GetProducts parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.cartProto.Product.GetProducts parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.cartProto.Product.GetProducts parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.cartProto.Product.GetProducts parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.cartProto.Product.GetProducts parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.cartProto.Product.GetProducts parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.cartProto.Product.GetProducts parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.cartProto.Product.GetProducts parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.cartProto.Product.GetProducts parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.cartProto.Product.GetProducts parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.cartProto.Product.GetProducts parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.cartProto.Product.GetProducts parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.cartProto.Product.GetProducts prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.cartProto.GetProducts}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.cartProto.GetProducts)
        com.example.cartProto.Product.GetProductsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.cartProto.Product.internal_static_com_example_cartProto_GetProducts_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.cartProto.Product.internal_static_com_example_cartProto_GetProducts_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.cartProto.Product.GetProducts.class, com.example.cartProto.Product.GetProducts.Builder.class);
      }

      // Construct using com.example.cartProto.Product.GetProducts.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
        } else {
          items_ = null;
          itemsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.cartProto.Product.internal_static_com_example_cartProto_GetProducts_descriptor;
      }

      @java.lang.Override
      public com.example.cartProto.Product.GetProducts getDefaultInstanceForType() {
        return com.example.cartProto.Product.GetProducts.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.cartProto.Product.GetProducts build() {
        com.example.cartProto.Product.GetProducts result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.cartProto.Product.GetProducts buildPartial() {
        com.example.cartProto.Product.GetProducts result = new com.example.cartProto.Product.GetProducts(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.example.cartProto.Product.GetProducts result) {
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
      }

      private void buildPartial0(com.example.cartProto.Product.GetProducts result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.cartProto.Product.GetProducts) {
          return mergeFrom((com.example.cartProto.Product.GetProducts)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.cartProto.Product.GetProducts other) {
        if (other == com.example.cartProto.Product.GetProducts.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.example.cartProto.Product.ProductListItem m =
                    input.readMessage(
                        com.example.cartProto.Product.ProductListItem.parser(),
                        extensionRegistry);
                if (itemsBuilder_ == null) {
                  ensureItemsIsMutable();
                  items_.add(m);
                } else {
                  itemsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.example.cartProto.Product.ProductListItem> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          items_ = new java.util.ArrayList<com.example.cartProto.Product.ProductListItem>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.cartProto.Product.ProductListItem, com.example.cartProto.Product.ProductListItem.Builder, com.example.cartProto.Product.ProductListItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
       */
      public java.util.List<com.example.cartProto.Product.ProductListItem> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
       */
      public com.example.cartProto.Product.ProductListItem getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
       */
      public Builder setItems(
          int index, com.example.cartProto.Product.ProductListItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
       */
      public Builder setItems(
          int index, com.example.cartProto.Product.ProductListItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
       */
      public Builder addItems(com.example.cartProto.Product.ProductListItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
       */
      public Builder addItems(
          int index, com.example.cartProto.Product.ProductListItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
       */
      public Builder addItems(
          com.example.cartProto.Product.ProductListItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
       */
      public Builder addItems(
          int index, com.example.cartProto.Product.ProductListItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.example.cartProto.Product.ProductListItem> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
       */
      public com.example.cartProto.Product.ProductListItem.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
       */
      public com.example.cartProto.Product.ProductListItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
       */
      public java.util.List<? extends com.example.cartProto.Product.ProductListItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
       */
      public com.example.cartProto.Product.ProductListItem.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.example.cartProto.Product.ProductListItem.getDefaultInstance());
      }
      /**
       * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
       */
      public com.example.cartProto.Product.ProductListItem.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.example.cartProto.Product.ProductListItem.getDefaultInstance());
      }
      /**
       * <code>repeated .com.example.cartProto.ProductListItem items = 1;</code>
       */
      public java.util.List<com.example.cartProto.Product.ProductListItem.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.cartProto.Product.ProductListItem, com.example.cartProto.Product.ProductListItem.Builder, com.example.cartProto.Product.ProductListItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.example.cartProto.Product.ProductListItem, com.example.cartProto.Product.ProductListItem.Builder, com.example.cartProto.Product.ProductListItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.example.cartProto.GetProducts)
    }

    // @@protoc_insertion_point(class_scope:com.example.cartProto.GetProducts)
    private static final com.example.cartProto.Product.GetProducts DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.cartProto.Product.GetProducts();
    }

    public static com.example.cartProto.Product.GetProducts getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetProducts>
        PARSER = new com.google.protobuf.AbstractParser<GetProducts>() {
      @java.lang.Override
      public GetProducts parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetProducts> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetProducts> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.cartProto.Product.GetProducts getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_cartProto_ProductListRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_cartProto_ProductListRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_cartProto_ProductListItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_cartProto_ProductListItem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_cartProto_GetProducts_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_cartProto_GetProducts_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rproduct.proto\022\025com.example.cartProto\"\'" +
      "\n\022ProductListRequest\022\021\n\tproductId\030\001 \003(\003\"" +
      "\177\n\017ProductListItem\022\n\n\002id\030\001 \001(\003\022\021\n\tlistIm" +
      "age\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\r\n\005price\030\004 \001(\t\022\014" +
      "\n\004type\030\005 \001(\t\022\020\n\010quantity\030\006 \001(\005\022\020\n\010discou" +
      "nt\030\007 \001(\t\"D\n\013GetProducts\0225\n\005items\030\001 \003(\0132&" +
      ".com.example.cartProto.ProductListItem2q" +
      "\n\016ProductService\022_\n\016getProductById\022).com" +
      ".example.cartProto.ProductListRequest\032\"." +
      "com.example.cartProto.GetProductsb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_cartProto_ProductListRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_cartProto_ProductListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_cartProto_ProductListRequest_descriptor,
        new java.lang.String[] { "ProductId", });
    internal_static_com_example_cartProto_ProductListItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_cartProto_ProductListItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_cartProto_ProductListItem_descriptor,
        new java.lang.String[] { "Id", "ListImage", "Name", "Price", "Type", "Quantity", "Discount", });
    internal_static_com_example_cartProto_GetProducts_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_cartProto_GetProducts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_cartProto_GetProducts_descriptor,
        new java.lang.String[] { "Items", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
